### ISSUE TITLE
Creating HTML forms for Inputs

### ISSUE THREAD

**Issue by Jmartz007** [Jmartz007/Wow_mythic_groups#1]
The current version of this program takes a dictionary with a player (main) and characters (main, alts). The dictionary is hard coded in right now but we need a way to be able to input the information needed either into a form on a webpage (ideal) a GUI or an excel/csv file. Then that information needs to be processed into a python dictionary.
The current format of the dictionary is:
{Player_name : {Character_name : { "Dungeon": dungeon, "Level": keylevel, "Class": wowclass, "Role": [list, healer, dps, etc]}, 
                         Another_character : {"Dungeon": another_dungeon, "Level": another_level, etc.}},
Another_Player : {Their_character_name: {"Dungeon": dungeon, "Level": keylevel", etc}}}

**Comment by fmaldone** [comment]
I'm ready! !!

**Comment by Jmartz007** [comment]
@fmaldone I ended up going with a template type framework and I am currently using your input html form as one of the pages. What I need from you is just a very nice looking html/css template for the site. Generic enough to be used on any of the pages. can you make a branch from the branch I linked to this issue called webapp and edit the /website/Templates/base.html file. 
Keep the:
`<div class="container">
        {% block content %}{% endblock %}
    </div>    `

**Comment by Jmartz007** [comment]
Did a merge with Main but there is still work to be done with the aesthetics and design of the HTML forms.
